### ISSUE TITLE
Checklist 공지 UI관련 이슈

### ISSUE THREAD

**Issue by MoojinChae** [DonutWorks/Ari#367]
- [ ] 아이폰 사파리, 아이폰 크롬에서 댓글을 수정하려면 두번 클릭 해야 한다.
- [ ] 할당 된 공지의 완료여부를 색으로만 표현하니 이해가 쉽지 않다.
- [ ] 체크리스트를 완료 하는 버튼이 댓글 옆에 있어서 헷갈린다.
- [ ] 관리자가 체크리스트를 볼 때 문자보내는 체크박스가 어떤 기능인지 알기 어렵다.
